services:
  fastfood-payment-service:
    image: ${DOCKER_REGISTRY-}fastfood-payment-service
    hostname: fastfood-payment-service
    restart: always
    networks:
      api:
        aliases:
          - payment_service.local
    build:
      context: .
      dockerfile: FastFoodPaymentService/Dockerfile
    volumes:
      - files:/home/api/files

volumes:
  files:
    external: false

networks:
  api: