name: Build and Deploy API to AKS

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: "fastfood-soat-rg"
  AKS_CLUSTER_NAME:     "fastfood-soat-aks"
  ACR_NAME:             "fastfoodsoatacr"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in the repository
        run: ls -R

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and Push Docker image
        run: |
          docker build -f FastFood/Dockerfile -t ${{ env.ACR_NAME }}.azurecr.io/fastfood-api:${{ github.sha }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/fastfood-api:${{ github.sha }}
          
      - name: Deploy to AKS
        run: |
          sed -i 's|image: .*|image: ${{ env.ACR_NAME }}.azurecr.io/fastfood-api:${{ github.sha }}|g' k8s/deployment-api.yaml

          kubectl apply -f k8s/